activation: gelu
alias: null
attn_dropout: 0.0
batch_normalization: false
batch_size: 32
drop_last_loader: false
dropout: 0.8
early_stop_patience_steps: -1
encoder_layers: 3
exclude_insample_y: false
fc_dropout: 0.2
futr_exog_list: null
h: 30
head_dropout: 0.0
hidden_size: 128
hist_exog_list: null
inference_windows_batch_size: 1024
input_size: 90
learn_pos_embed: true
learning_rate: 0.012752156347146538
linear_hidden_size: 256
loss: &id001 !!python/object:neuralforecast.losses.pytorch.HuberLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  delta: 1.0
  horizon_weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDQAAADE4Nzc5ODkxMjgwMzJxAlgDAAAAY3B1cQNLHk50cQRRLoACXXEAWA0AAAAxODc3
      OTg5MTI4MDMycQFhLh4AAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/
      AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A
      AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/
  - 0
  - !!python/tuple
    - 30
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: false
max_steps: 500
n_heads: 16
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
patch_len: 16
random_seed: 14
res_attention: true
revin: true
revin_affine: false
revin_subtract_last: true
scaler_type: standard
start_padding_enabled: false
stat_exog_list: null
step_size: 1
stride: 8
val_check_steps: 100
valid_batch_size: null
valid_loss: *id001
windows_batch_size: 128
